### ISSUE TITLE
Enemy - Individual healthbar

### ISSUE THREAD

**Issue by emilholmen** [Botched135/Project-Perkele#15]
Who: Enemies
What: A small health bar above each enemy.
Why: To get a easy view of the individual enemies health.
Time Est.: 1 days~
Prio: 2st

**Comment by emilholmen** [comment]
I recommend stacking two rectangles and just decrease the size of a red one/top one according to the enemy's percentage of life.
Being able to toggle it with a key would also be nice :)

**Comment by Botched135** [comment]
The toogle key is the only thing I am missing, then it is COMPLETLY done
