### ISSUE TITLE
Player/Enemy/Loot - Additional types of stats

### ISSUE THREAD

**Issue by emilholmen** [Botched135/Project-Perkele#19]
Who: Player/Enemy/Loot
What: Additional stats which makes sense in the context of hack'n'slash, and the given fantasy universe. More defensive, offensive and utility stats would be cool. Makes for a broader variation of item stat combinations also.
Why: To add another level of complexity to the game play (more reason to go kill stuff and farm loot!).
Time Est.: N/A (ongoing issue, more stat types could be added as time goes).
Prio: 2st

**Comment by emilholmen** [comment]
When a new type of stat is wanted, just make a new issue specifying it (and the necessary info regarding it).

**Comment by Hethix** [comment]
Implemented the lifeRegen stat to armor
