### ISSUE TITLE
Tilemap (in-game background)

### ISSUE THREAD

**Issue by emilholmen** [Botched135/Project-Perkele#26]
Who: Game
What: Import a tilemap to use as background.
Why: To have a nicely looking background
Time Est.: 2 hour
Prio: 1st

**Comment by emilholmen** [comment]
Randomized or fixed repeating patches?

**Comment by Botched135** [comment]
I would prefer Randomized

**Comment by emilholmen** [comment]
Same, just takes a bit longer, lets see how long we got :)
