### ISSUE TITLE
Write the WIKI

### ISSUE THREAD

**Issue by emilholmen** [Botched135/Project-Perkele#34]
- UML class diagram
- (Flow diagram of workform. Waterfall, SCRUM or other?)
- Description of original game
- Description of our game
  - What our game took and didn't take from the original
  - The goal/win condition (ours is endless tho')
  - The lose condition
  - How to play/controls

**Comment by Botched135** [comment]
Description of original game
Description of our game
What our game took and didn't take from the original
The goal/win condition (ours is endless tho')
The lose condition
How to play/controls

DONE!
